# Model Config
### TEST CONFIG FOR MVP

RSC_ROOT: "../../../data/"
STOCK_FOLDER: "Aktien/"
ETF_FOLDER: "ETF/"
MODEL_FOLDER: "../../../CNN/predictionApi/modelDir/"
MODELS_TO_LOAD: [
  "30_480_1_AAPL1312024_159.pt", "30_480_6_AAPL1312024_1644.pt"
]

RSC_DATA_FILES: [
  #key: [fileName, [columns in file], [relevant feature columns], y-variable]
  AAPL: ["AAPL_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"]]
]

FEATURES_DATA_TO_LOAD : [
  #key: [fileName, [columns in file], [relevant feature columns]
  EWA: ["EWA_1min.txt", ["DateTime", "Open_EWA", "a", "b", "c", "Volume"], ["DateTime", "Open_EWA"]],
  EWC: ["EWC_1min.txt", ["DateTime", "Open_EWC", "a", "b", "c", "Volume"], ["DateTime", "Open_EWC"]],
  EWG: ["EWG_1min.txt", ["DateTime", "Open_EWG", "a", "b", "c", "Volume"], ["DateTime", "Open_EWG"]],
  EWJ: ["EWJ_1min.txt", ["DateTime", "Open_EWJ", "a", "b", "c", "Volume"], ["DateTime", "Open_EWJ"]],
  EWU: ["EWU_1min.txt", ["DateTime", "Open_EWU", "a", "b", "c", "Volume"], ["DateTime", "Open_EWU"]],
  INDA: ["INDA_1min.txt", ["DateTime", "Open_INDA", "a", "b", "c", "Volume"], ["DateTime", "Open_INDA"]],
  MCHI: ["MCHI_1min.txt", ["DateTime", "Open_MCHI", "a", "b", "c", "Volume"], ["DateTime", "Open_MCHI"]]
]

FEATURES: [
  "Open", "Volume", "Open_EWA", "Open_EWC", "Open_EWG", "Open_EWJ", "Open_EWU", "Open_INDA", "Open_MCHI"
]

