# Define services for the Docker Compose configuration
services:

  # Service to train a transformer model
  train_transformer:
    # Specify the build context for this service (current directory)
    build:
      context: .

    # Bind mount the current directory to /app in the container
    volumes:
      - .:/app

    # Map port 5001 on the host to port 5001 in the container
    ports:
      - 5001:5001

    # Specify the command to run when the container starts
    command:
      [
        "python",
        "-m",
        "src_transformers.main",
        "-c",
        "data/test_configs/training_config_slp.yaml",
        "-p",
        "train"
      ]

  # Service to use a trained transformer model to predict
  predict_transformer:
    # Specify the build context for this service (current directory)
    build:
      context: .

    # Bind mount the current directory to /app in the container
    volumes:
      - .:/app

    # Map port 5001 on the host to port 5001 in the container
    ports:
      - 5002:5002

    # Specify the command to run when the container starts
    command:
      [
        "python",
        "-m",
        "src_transformers.main",
        "-c",
        "data/test_configs/training_config_slp.yaml",
        "-p",
        "predict"
      ]
