# To only start a specific services, run: docker compose up <service_name> 
# (e.g. docker compose up train_transformer)

# Define services for the Docker Compose configuration
services:

  base_service:
    # Specify the build context for this service (current directory)
    build:
      context: .

    # Bind mount the current directory to /app in the container
    volumes:
      - .:/app

  # Service to train a transformer model
  train_transformer:

    # This service extends the base_service
    extends:
      service: base_service

    # Map port 5001 on the host to port 5001 in the container
    ports:
      - 5001:5001

    # Specify the command to run when the container starts
    # This command starts the training process
    command:
      [
        "python",
        "-m",
        "src_transformers.main",
        "-c",
        "data/test_configs/training_config_slp.yaml",
        "-p",
        "train",
        "-d",
        "data/test_configs/data_config.yaml"
      ]

  # Service to use a trained transformer model to predict
  predict_transformer:

    # This service extends the base_service
    extends:
      service: base_service

    # Map port 5002 on the host to port 5002 in the container
    ports:
      - 5002:5002

    # Specify the command to run when the container starts
    # This command starts the prediction process
    command:
      [
        "python",
        "-m",
        "src_transformers.main",
        "-c",
        "data/test_configs/training_config_slp.yaml",
        "-p",
        "predict",
        "-d",
        "data/test_configs/data_config.yaml"
      ]

  # Service to visualize data
  vizualize_data:

    # This service extends the base_service
    extends:
      service: base_service

    # Map port 5003 on the host to port 5003 in the container
    ports:
      - 5003:5003

    # Specify the command to run when the container starts
    # This command starts the visualization process
    command:
      [
        "python",
        "-m",
        "src_transformers.utils.visualize_data",
        "data/test_configs/data_config.yaml"
      ]

  test_data:

    # This service extends the base_service
    extends:
      service: base_service

    # Map port 5004 on the host to port 5004 in the container
    ports:
      - 5004:5004

    # Specify the command to run when the container starts
    # This command tests if the dataloader and the dataset are working as expected
    command:
      [
        "python",
        "-m",
        "src_transformers.preprocessing.perSymbolDataset",
        "data/test_configs/data_config.yaml"
      ]
