# To only start a specific services, run: docker compose up <service_name> 
# (e.g. docker compose up train_transformer)

# Define services for the Docker Compose configuration
services:

  base_service:

    #runtime: nvidia # Specify the NVIDIA runtime for GPU support
    #environment:
    #- NVIDIA_VISIBLE_DEVICES=all # Specify which GPUs to use

    # Specify the build context for this service (current directory)
    build:
      context: .

    # Bind mount the current directory to /app in the container
    volumes:
      - .:/app

  # Service to train a transformer model
  train_transformer:

    # This service extends the base_service
    extends:
      service: base_service

    # Map port 5001 on the host to port 5000 in the container
    ports:
      - 5001:5000

    # Specify the command to run when the container starts
    # This command starts the training process
    command:
      [
        "python",
        "-m",
        "src_transformers.main",
        "-c",
        "data/test_configs/training_config_slp.yaml",
        "-p",
        "train",
        "-d",
        "data/test_configs/data_config_multivariat.yaml"
      ]

  # Service to use a trained transformer model to predict
  predict_transformer:

    # This service extends the base_service
    extends:
      service: base_service

    # Map port 5002 on the host to port 5000 in the container
    ports:
      - 5002:5000

    # Specify the command to run when the container starts
    # This command starts the prediction process
    command:
      [
        "python",
        "-m",
        "src_transformers.main",
        "-c",
        "data/test_configs/training_config_slp.yaml",
        "-p",
        "predict",
        "-d",
        "data/test_configs/data_config_multivariat.yaml"
      ]

  # Service to visualize data
  vizualize_data:

    # This service extends the base_service
    extends:
      service: base_service

    # Map port 5003 on the host to port 5000 in the container
    ports:
      - 5003:5000

    # Specify the command to run when the container starts
    # This command starts the visualization process
    command:
      [
        "python",
        "-m",
        "src_transformers.utils.visualize_data",
        "data/test_configs/training_config.yaml"
      ]
