version: '3.9'

networks:
  backend_network:
    driver: bridge

services:
  backend:
    build:
      context: ./WebApp/services/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./WebApp/services/backend:/app
    entrypoint:
      ["bash", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000"]
    networks:
      - backend_network

  # Service to use a trained transformer model to predict
  predict_transformer:
    # Specify the build context for this service (current directory)
    build:
      context: ./transformer
      dockerfile: Dockerfile
    
    # Bind mount the current directory to /app in the container
    volumes:
      - ./transformer:/app
    
    # Map port 8001 on the host to port 8000 in the container
    ports:
      - 8001:8000

    # Set the entrypoint of the container to start a Uvicorn server running the app defined in 'api' of 'src_transformers' directory
    entrypoint:
      ["bash", "-c", "cd src_transformers && uvicorn api:app --host 0.0.0.0 --port 8000"]
    networks:
      - backend_network

  # Service to use a trained transformer model to predict
  predict_cnn:
    # Specify the build context for this service (current directory)
    build:
      context: ./CNN
      dockerfile: Dockerfile
    
    # Bind mount the current directory to /app in the container
    volumes:
      - ./CNN:/app
      - ./data:/data
    
    # Map port 8002 on the host to port 8000 in the container
    ports:
      - 8002:8000

    # Set the entrypoint of the container to start a Uvicorn server running the app defined in 'api' of 'src_transformers' directory
    entrypoint:
      ["bash", "-c", "uvicorn api:app --host 0.0.0.0 --port 8000"]
    networks:
      - backend_network

  predict_ann:
    # Specify the build context for this service (current directory)
    build:
      context: ./ann
      dockerfile: Dockerfile
    
    # Bind mount the current directory to /app in the container
    volumes:
      - ./ann:/app
    
    # Map port 8003 on the host to port 8000 in the container
    ports:
      - 8003:8000

    # Set the entrypoint of the container to start a Uvicorn server running the app defined in 'api' of 'src_transformers' directory
    entrypoint:
      ["bash", "-c", "uvicorn api:app --host 0.0.0.0 --port 8000"]
    networks:
      - backend_network

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: services/frontend/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./services/frontend:/app
  #   environment:
  #     - VUE_APP_API_URL=http://localhost:8000
  #   depends_on:
  #     - backend
