version: "3.9"

networks:
  backend_network:
    driver: bridge

services:
  backend:
    build:
      context: ./WebApp/services/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./WebApp/services/backend:/app
      - ./data:/data
    entrypoint:
      [
        "bash",
        "-c",
        "uvicorn main:app --host 0.0.0.0 --port 8000"
      ]
    networks:
      - backend_network

  frontend:
    # user: "node"
    build:
      context: ./WebApp/services/frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # Set the entrypoint of the container to start the frontend
    entrypoint: [ "bash", "-c", "npm run serve" ]
    depends_on:
      - backend
    networks:
      - backend_network

  # Service to use a trained transformer model to predict
  predict_transformer:
    # Specify the build context for this service (current directory)
    build:
      context: ./transformer
      dockerfile: Dockerfile

    # Bind mount the current directory to /app in the container
    volumes:
      - ./transformer:/app

    # Map port 8001 on the host to port 8000 in the container
    ports:
      - 8001:8000

    # Set the entrypoint of the container to start a Uvicorn server running the app defined in 'api' of 'src_transformers' directory
    entrypoint:
      [
        "bash",
        "-c",
        "uvicorn api:app --host 0.0.0.0 --port 8000"
      ]
    networks:
      - backend_network

  # Service to use a trained transformer model to predict
  predict_cnn:
    # Specify the build context for this service (current directory)
    build:
      context: ./CNN
      dockerfile: Dockerfile

    # Bind mount the current directory to /app in the container
    volumes:
      - ./CNN:/app
      - ./data:/data

    # Map port 8002 on the host to port 8000 in the container
    ports:
      - 8002:8000

    # Set the entrypoint of the container to start a Uvicorn server running the app defined in 'api' of 'src_transformers' directory
    entrypoint:
      [
        "bash",
        "-c",
        "uvicorn api:app --host 0.0.0.0 --port 8000"
      ]
    networks:
      - backend_network

  predict_ann:
    # Specify the build context for this service (current directory)
    build:
      context: ./ann
      dockerfile: Dockerfile

    # Bind mount the current directory to /app in the container
    volumes:
      - ./ann:/app

    # Map port 8003 on the host to port 8000 in the container
    ports:
      - 8003:8000

    # Set the entrypoint of the container to start a Uvicorn server running the app defined in 'api' of 'src_transformers' directory
    entrypoint:
      [
        "bash",
        "-c",
        "uvicorn api:app --host 0.0.0.0 --port 8000"
      ]
    networks:
      - backend_network
