AMOUNT_OF_DATA : 1
TO_FIND_RSC_FOLDER : "C:\\Projekte\\__PorjectDeepLearningMain\\Deep_Learning\\CNN\\data\\raw_data\\Aktien\\"
TO_SAVE_RSC_FOLDER : "C:\\Projekte\\__PorjectDeepLearningMain\\Deep_Learning\\CNN\\data\\train_data\\"
TO_FIND_OTHER_FEATURE_RSC_FOLDER : "C:\\Projekte\\__PorjectDeepLearningMain\\Deep_Learning\\CNN\\data\\raw_data\\ETF\\"

##AAPL,AAL,AMD,C,MRNA,NIO,NVDA,SNAP,SQ,TSLA
RSC_DATA_FILES: [
  #key: [fileName, [columns in file], [relevant feature columns], y-variable]
  #AAL: ["AAL_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  #AAPL: ["AAPL_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  #AMD: ["AMD_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  #C: ["C_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  MRNS: ["MRNS_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  NIO: ["NIO_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  NVDA: ["NVDA_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  SNAP: ["SNAP_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  SQ: ["SQ:_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"],
  TSLA: ["TSLA_1min.txt", [ "DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume" ], "Open" ]
]

OTHER_FEATURES_TO_LOAD : [
  #key: [fileName, [columns in file], [relevant columns to keep]
  #EWA: ["EWA_1min.txt", ["DateTime", "Open_EWA", "a", "b", "c", "Volume"], ["DateTime", "Open_EWA"]], #Australia
  #EWC: ["EWC_1min.txt", ["DateTime", "Open_EWC", "a", "b", "c", "Volume"], ["DateTime", "Open_EWC"]], #Canda
  #EWG: ["EWG_1min.txt", ["DateTime", "Open_EWG", "a", "b", "c", "Volume"], ["DateTime", "Open_EWG"]], #Germany
  #EWJ: ["EWJ_1min.txt", ["DateTime", "Open_EWJ", "a", "b", "c", "Volume"], ["DateTime", "Open_EWJ"]], #Japan
  #EWU: ["EWU_1min.txt", ["DateTime", "Open_EWU", "a", "b", "c", "Volume"], ["DateTime", "Open_EWU"]], #England
  #INDA: ["INDA_1min.txt", ["DateTime", "Open_INDA", "a", "b", "c", "Volume"], ["DateTime", "Open_INDA"]], #Inda
  #MCHI: ["MCHI_1min.txt", ["DateTime", "Open_MCHI", "a", "b", "c", "Volume"], ["DateTime", "Open_MCHI"]] #China
  MCHI: ["MCHI_1min.txt", ["DateTime", "Open_MCHI", "a", "b", "c", "Volume"], ["DateTime", "Open_MCHI"]], #China
  IVV: ["IVV_1min.txt", ["DateTime", "Open_IVV", "a", "b", "c", "Volume"], ["DateTime", "Open_IVV"]] #USA
]

TIME_SPAN_BEGIN: "2005-01-01"
TIME_SPAN_END: "2021-01-30"
TIMESERIES_SEQUENCE_LEN: 20  # length  of the TimeSeries; 1 : no series at all
TIMESTEPS_AHEAD: 12  # predict 60min
TIME_STEP_INTERVAL: 300  #
TOLERANCE: 100
NEXT_DAY_RETRY_THRESHOLD: 8

FEATURES: [
  "Open", "Volume", "Open_MCHI", "Open_IVV"
]
MVG_AVG: True #if moving Avg should be a feature

DATA_FEATURE_NAME: "DATA_Open_Volume_MCHI_IVV_MVG_ahead12"
ALLOW_SERIES_INTERVAL_TOLERANCE: true
ENHANCE_DIFFERENCE: true
