AMOUNT_OF_DATA : 1
TO_FIND_RSC_FOLDER : "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\Aktien\\"
TO_SAVE_RSC_FOLDER : "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\MAIN_DATA\\"
TO_SAVE_IMAGE_RSC_FOLDER : "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\MAIN_DATA\\imageData\\"
TO_SAVE_TS_RSC_FOLDER : "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\MAIN_DATA\\timeSeriesData\\"

##AAPL,AAL,AMD,C,MRNA,NIO,NVDA,SNAP,SQ,TSLA
RSC_DATA_FILES: [
  #key: [fileName, [columns in file], [relevant feature columns], y-variable]
  AAPL: ["AAPL_1min.txt", ["DateTime", "Open", "a", "b", "c", "Volume"], ["DateTime", "Open", "Volume"], "Open"]
]

TO_FIND_OTHER_FEATURE_RSC_FOLDER : "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\ETF\\"
TO_SAVE_OTHER_FEATURE_RSC_FOLDER : "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\FEATURE_DATA\\"
TO_SAVE_OTHER_FEATURE_IMG_RSC_FOLDER : "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\FEATURE_DATA\\"
OTHER_FEATURES_TO_LOAD : [
  #key: [fileName, [columns in file], [relevant feature columns]
  EWA: ["EWA_1min.txt", ["DateTime", "Open_EWA", "a", "b", "c", "Volume"], ["DateTime", "Open_EWA"]],
  EWC: ["EWC_1min.txt", ["DateTime", "Open_EWC", "a", "b", "c", "Volume"], ["DateTime", "Open_EWC"]],
  EWG: ["EWG_1min.txt", ["DateTime", "Open_EWG", "a", "b", "c", "Volume"], ["DateTime", "Open_EWG"]],
  EWJ: ["EWJ_1min.txt", ["DateTime", "Open_EWJ", "a", "b", "c", "Volume"], ["DateTime", "Open_EWJ"]],
  EWU: ["EWU_1min.txt", ["DateTime", "Open_EWU", "a", "b", "c", "Volume"], ["DateTime", "Open_EWU"]],
  INDA: ["INDA_1min.txt", ["DateTime", "Open_INDA", "a", "b", "c", "Volume"], ["DateTime", "Open_INDA"]],
  MCHI: ["MCHI_1min.txt", ["DateTime", "Open_MCHI", "a", "b", "c", "Volume"], ["DateTime", "Open_MCHI"]]
]

TIME_SPAN_BEGIN: "2014-01-01"
TIME_SPAN_END: "2014-05-30"
TIMESERIES_SEQUENCE_LEN: 20  # length  of the TimeSeries; 1 : no series at all
TIMESTEPS_AHEAD: 1  # predict 60min
TIME_STEP_INTERVAL: 120  #
TOLERANCE: 180 #5 day tolerance allowed.. to hight but neccessary

FEATURES: [
  "Open", "Volume", "Open_EWA", "Open_EWC", "Open_EWG", "Open_EWJ", "Open_EWU", "Open_INDA", "Open_MCHI"
]

#todo automatically
DATA_FEATURE_NAME: "DATA"
ALLOW_SERIES_INTERVAL_TOLERANCE: true
ENHANCE_DIFFERENCE: true

#Für alle Modelle ändern immer = TIMESTEPS_AHEAD + 1 bis auf 6. DATA_FEATURE_NAME=..
#für APPL 6x danach andere aktie und von vorne...
