# Model Config
#### HYPER PARAMETER ####
NUM_EPOCH: 4
LR: 0.0001
BATCH_SIZE: 1
TRAIN_TEST_SPLIT_RATIO: 0.8 #To test smaller the training size
L2RegularisationFactor: 0.00 #First Overfit
DROPOUT: 0.0 #First Overfit
LOGGING_INTERVAL: 10 #every x value will be logged
LOSS_PLOT_INTERVAL: 1000
PROJECT_ROOT : "C:\\Projekte\\__PorjectDeepLearningMain\\Deep_Learning\\CNN\\"
RESULT_FOLDER: "C:\\Projekte\\__PorjectDeepLearningMain\\Deep_Learning\\CNN\\src\\training\\result\\"
RSC_DATA_ROOT: "C:\\Projekte\\__PorjectDeepLearningMain\\Deep_Learning\\CNN\\data\\train_data\\"
TRAINING_FOLDER: "swingTrayding_20_120_10_DATA_Open_Volume_MCHI_IVV_MVG_ahead10\\"
MODEL_NAME: "20_120_10_swingTrayding_4"
TRAINING_DATA_LIST: [
  #Training_Data, "Label_Data
  #AAL: ["AAL\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "AAL\\ImageGafData\\LABELS.npy"],
  #AAPL: ["AAPL\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "AAPL\\ImageGafData\\LABELS.npy"],
  #AMD: ["AMD\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "AMD\\ImageGafData\\LABELS.npy"],
  #C: ["C\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "C\\ImageGafData\\LABELS.npy"],
  MRNS: [ "MRNS\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "MRNS\\ImageGafData\\LABELS.npy" ],
  NIO: [ "NIO\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "NIO\\ImageGafData\\LABELS.npy" ],
  NVDA: [ "NVDA\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "NVDA\\ImageGafData\\LABELS.npy" ],
  SNAP: [ "SNAP\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "SNAP\\ImageGafData\\LABELS.npy" ],
  SQ: [ "SQ\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "SQ\\ImageGafData\\LABELS.npy" ],
  TSLA: [ "TSLA\\ImageGafData\\DATA_Open_Volume_MCHI_IVV_MVG_ahead10.npy", "TSLA\\ImageGafData\\LABELS.npy" ]
]
FEATURE_LIST: [
  "Open", "Volume", "Open_MCHI", "Open_IVV", "mvgAvg"
]