# Model Config
#### HYPER PARAMETER ####
NUM_EPOCH: 5
LR: 0.01
BATCH_SIZE: 1
TRAIN_TEST_SPLIT_RATIO: 0.9 #To test smaller the training size
L2RegularisationFactor: 0.00 #First Overfit
DROPOUT: 0.0 #First Overfit
LOGGING_INTERVAL: 10 #every x value will be logged
LOSS_PLOT_INTERVAL: 1000
RESULT_FOLDER: "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\result\\"
RSC_DATA_ROOT: "C:\\Projekte\\ProjectDeepLearning_CNN\\project_deeplearning\\test\\data\\MAIN_DATA\\"
TRAINING_FOLDER: "20_120_1_DATA_2014-01-01_2014-05-30\\"
TRAINING_DATA_LIST: [
  #Training_Data, "Label_Data
  AAPL: ["AAPL\\ImageGafData\\DATA.npy", "AAPL\\ImageGafData\\LABELS.npy"],
]
FEATURE_LIST: [
  "Open", "Open_EWA", "Open_EWC", "Open_EWG", "Open_EWJ", "Open_EWU", "Open_INDA", "Open_MCHI"
]
MODEL_NAME: "20_120_1_AAPL" # must be equal to training_folder